name: Ticket template
description: Create a ticket to help us improve
labels: ['NEW!']
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below.
        > [!IMPORTANT]
        > Do not forget to add specific labels!

        Markdown styling info: [GitHub Documentation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#headings)
  
